apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  labels:
    app: httpd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: front-end
        image: httpd
        ports:
        - containerPort: 80
